name: graph_calculator_clock
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  auto_size_text: ^2.1.0
  weather_icons: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Digital-7 Mono
      fonts:
        - asset: third_party/digital-7/digital-7-mono.ttf
